// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #KubeVirtInput is the `kubevirt` verb's plugin_input: the method name plus its
// method-exclusive modifiers.
type KubeVirtInput struct {
	// method — the kubevirt method name; the verb's PRIMARY input field, so
	// `kubevirt: vm` desugars to {method: "vm"}.
	Method string `yaml:"method,omitempty" json:"method"`

	// name / namespace — resource identity.
	Name string `yaml:"name,omitempty" json:"name,omitempty"`

	Namespace string `yaml:"namespace,omitempty" json:"namespace,omitempty"`

	// cluster — a kind:kubernetes cluster template name; this PLUGIN self-resolves it
	// to a concrete kube_context (self-loading the project) and leaves the authored key
	// in place, so the input def admits both.
	Cluster string `yaml:"cluster,omitempty" json:"cluster,omitempty"`

	// kubeconfig / kube_context — the cluster-selection pair (kubeconfig path +
	// context) an authored step may set explicitly.
	Kubeconfig string `yaml:"kubeconfig,omitempty" json:"kubeconfig,omitempty"`

	KubeContext string `yaml:"kube_context,omitempty" json:"kube_context,omitempty"`

	// wait / timeout seconds for the readiness-oriented methods (wait-ready,
	// guest-info, migration, datavolume, snapshot).
	WaitSeconds int `yaml:"wait_seconds,omitempty" json:"wait_seconds,omitempty"`

	// to_node — the migration target node (method: migration).
	ToNode string `yaml:"to_node,omitempty" json:"to_node,omitempty"`

	// snapshot_class — the VolumeSnapshotClass (method: snapshot).
	SnapshotClass string `yaml:"snapshot_class,omitempty" json:"snapshot_class,omitempty"`

	// description — a human label for a created snapshot/datavolume.
	Description string `yaml:"description,omitempty" json:"description,omitempty"`

	// size — the DataVolume size (method: datavolume).
	Size string `yaml:"size,omitempty" json:"size,omitempty"`

	// storage_class — the DataVolume/snapshot storage class.
	StorageClass string `yaml:"storage_class,omitempty" json:"storage_class,omitempty"`

	// source_manifest — a multi-doc KubeVirt YAML manifest path the datavolume/vm
	// methods may apply verbatim.
	SourceManifest string `yaml:"source_manifest,omitempty" json:"source_manifest,omitempty"`

	// local_port — the local TCP port for `virtctl port-forward` (method: port-forward);
	// 0 auto-allocates a free port.
	LocalPort int `yaml:"local_port,omitempty" json:"local_port,omitempty"`

	// remote_port — the guest port to forward (method: port-forward; default 22).
	RemotePort int `yaml:"remote_port,omitempty" json:"remote_port,omitempty"`

	// json — machine-readable output toggle (methods: vm/vmi/datavolume/snapshot).
	JSON bool `yaml:"json,omitempty" json:"json,omitempty"`
}
